export default {
  add: "Add",
  edit: "Edit",
  delete: "Delete",
  search: "Search",
  reset: "Reset",
  confirm: "Confirm",
  cancel: "Cancel",
  save: "Save",
  submit: "Submit",
  export: "Export",
  import: "Import",
  copy: "Copy",
  paste: "Paste",
  cut: "Cut",
  baseInfo: "Base Info",

  createdDt: "Created Date",
  updatedDt: "Updated Date",
  noData: "No Data",

  menu: {
    task: "Task",
    history: "History",
    config: {
      settings: "Settings",
      general: "General Config",
      llm: "LLM Config",
      theme: "Theme Config"
    }
  },
  user: "User",
  switchModel: "Switch Model",
  step: "Step",
  promptInputPlaceHolder: "Please Input Task Prompt",
  promptInput: "Prompt Input",
  promptInputKw: "Prompt Input",
  clearCacheSuccess: "Clear cache success",
  openManusAgiTips: "The above content is generated by OpenManus for reference only",
  taskStatus: {
    name: "Task Status",
    success: "Success",
    failed: "Failed",
    running: "Running",
    terminated: "Terminated",
  },
  newTask: "New Task",

}
